// app/tos/page.tsx
export default function Page() {
  return (
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-4xl font-bold bg-gradient-to-r from-violet-600 to-indigo-500 bg-clip-text text-transparent mb-6">
        Terms of Service & Privacy Policy
      </h1>
      <p className="text-slate-500 dark:text-slate-400 mb-8">Last Updated: 3 Nov 2023.</p>

      <div className="prose prose-slate dark:prose-invert max-w-none">
        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. Introduction</h2>
          <p className="text-slate-600 dark:text-slate-300">
            Welcome to TokenStork.com. These Terms of Service govern your use of the website operated by George Donnelly, doing business as Panmoni. By accessing or using our website, you agree to be bound by these Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. Eligibility</h2>
          <p className="text-slate-600 dark:text-slate-300">
            You must be at least 18 years old to access or use the website. By agreeing to these Terms, you represent and warrant that you are at least 18 years old.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. Website Content</h2>
          <p className="text-slate-600 dark:text-slate-300">
            The content provided on this website is for informational purposes only and does not constitute financial advice. We provide information regarding various cryptocurrency tokens, however, we do not endorse or recommend any such tokens. Investing in cryptocurrency tokens involves various risks including, but not limited to, the loss of principal, liquidity risk, and market volatility.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Intellectual Property</h2>
          <p className="text-slate-600 dark:text-slate-300">
            All TokenStork trademarks on or related to the website are the exclusive property of Panmoni or its licensors. You may not reproduce, distribute, or create derivative works based on our content without explicit written permission.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">5. Disclaimer of Warranties</h2>
          <p className="text-slate-600 dark:text-slate-300">
            The website and its content are provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind, either express or implied, to the fullest extent permissible under applicable law.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">6. Indemnification</h2>
          <p className="text-slate-600 dark:text-slate-300">
            You agree to indemnify, defend, and hold harmless Panmoni, its affiliates, officers, directors, employees, agents, and licensors from and against all claims, damages, losses, expenses (including legal fees) arising from your use of the website or violation of these Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">7. Third-Party Links</h2>
          <p className="text-slate-600 dark:text-slate-300">
            We are not responsible for any third-party content, links, or services provided on or through the website. Your interactions with third-party entities, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and the third-party.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">8. Limitation of Liability</h2>
          <p className="text-slate-600 dark:text-slate-300">
            To the maximum extent permitted by law, Panmoni and its affiliates, directors, employees, or licensors shall not be liable for any direct, indirect, punitive, incidental, special, or consequential damages arising out of or in any way connected with your use of the website.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">9. Accuracy of Information</h2>
          <p className="text-slate-600 dark:text-slate-300">
            While we strive to provide accurate information, we do not guarantee the accuracy, completeness, or timeliness of the information on the website.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">10. No Endorsement</h2>
          <p className="text-slate-600 dark:text-slate-300">
            Mention of third-party products, services, or organizations on TokenStork.com does not constitute an endorsement.
          </p>
        </section>

        <section className="mb-8 border-t border-slate-200 dark:border-slate-800 pt-8 mt-8">
          <h2 className="text-3xl font-bold bg-gradient-to-r from-violet-600 to-indigo-500 bg-clip-text text-transparent mb-6">
            Privacy Policy
          </h2>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">1. Introduction</h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            Your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website, TokenStork.com.
          </p>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">2. Information We Collect</h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            When you visit TokenStork.com, we try not to collect any information about you whatsoever, however CloudFlare and Vercel likely collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies installed on your device.
          </p>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">3. Use of Your Information</h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            We may use Google Analytics data generally to improve and optimize our site (for example, by generating analytics about how our customers browse and interact with the site, and to assess the success of our marketing and advertising campaigns).
          </p>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">4. Sharing Your Information</h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            We share your Device Information with third parties to help us use your Device Information, as described above. We use Google Analytics to help us understand how our customers use the site. You can read more about how Google uses your Personal Information <a href="https://www.google.com/intl/en/policies/privacy/" className="text-violet-600 hover:underline">here</a>. You can also opt-out of Google Analytics <a href="https://tools.google.com/dlpage/gaoptout" className="text-violet-600 hover:underline">here</a>.
          </p>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">5. Security</h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            We employ reasonable security measures to protect your information from unauthorized access, alteration, disclosure, or destruction.
          </p>

          <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">6. Contact Information</h3>
          <p className="text-slate-600 dark:text-slate-300">
            For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at <a href="mailto:hello@panmoni.com" className="text-violet-600 hover:underline">hello@panmoni.com</a>.
          </p>
        </section>
      </div>
    </main>
  );
}

// src/routes/tos/+page.svelte
<svelte:head>
	<title>Terms of Service &amp; Privacy — Token Stork</title>
</svelte:head>

<main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
	<h1 class="text-4xl font-bold bg-gradient-to-r from-violet-600 to-indigo-500 bg-clip-text text-transparent mb-6">
		Terms of Service &amp; Privacy Policy
	</h1>
	<p class="text-slate-500 dark:text-slate-400 mb-8">Last Updated: 3 Nov 2023.</p>

	<div class="prose prose-slate dark:prose-invert max-w-none">
		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. Introduction</h2>
			<p class="text-slate-600 dark:text-slate-300">
				Welcome to TokenStork.com. These Terms of Service govern your use of the website operated by George Donnelly, doing business as Panmoni. By accessing or using our website, you agree to be bound by these Terms.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. Eligibility</h2>
			<p class="text-slate-600 dark:text-slate-300">
				You must be at least 18 years old to access or use the website. By agreeing to these Terms, you represent and warrant that you are at least 18 years old.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. Website Content</h2>
			<p class="text-slate-600 dark:text-slate-300">
				The content provided on this website is for informational purposes only and does not constitute financial advice. We provide information regarding various cryptocurrency tokens, however, we do not endorse or recommend any such tokens. Investing in cryptocurrency tokens involves various risks including, but not limited to, the loss of principal, liquidity risk, and market volatility.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Intellectual Property</h2>
			<p class="text-slate-600 dark:text-slate-300">
				All TokenStork trademarks on or related to the website are the exclusive property of Panmoni or its licensors. You may not reproduce, distribute, or create derivative works based on our content without explicit written permission.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">5. Disclaimer of Warranties</h2>
			<p class="text-slate-600 dark:text-slate-300">
				The website and its content are provided "as is" and "as available" without any warranties of any kind, either express or implied, to the fullest extent permissible under applicable law.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">6. Indemnification</h2>
			<p class="text-slate-600 dark:text-slate-300">
				You agree to indemnify, defend, and hold harmless Panmoni, its affiliates, officers, directors, employees, agents, and licensors from and against all claims, damages, losses, expenses (including legal fees) arising from your use of the website or violation of these Terms.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">7. Third-Party Links</h2>
			<p class="text-slate-600 dark:text-slate-300">
				We are not responsible for any third-party content, links, or services provided on or through the website. Your interactions with third-party entities, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and the third-party.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">8. Limitation of Liability</h2>
			<p class="text-slate-600 dark:text-slate-300">
				To the maximum extent permitted by law, Panmoni and its affiliates, directors, employees, or licensors shall not be liable for any direct, indirect, punitive, incidental, special, or consequential damages arising out of or in any way connected with your use of the website.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">9. Accuracy of Information</h2>
			<p class="text-slate-600 dark:text-slate-300">
				While we strive to provide accurate information, we do not guarantee the accuracy, completeness, or timeliness of the information on the website.
			</p>
		</section>

		<section class="mb-8">
			<h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-4">10. No Endorsement</h2>
			<p class="text-slate-600 dark:text-slate-300">
				Mention of third-party products, services, or organizations on TokenStork.com does not constitute an endorsement.
			</p>
		</section>

		<section id="privacy" class="mb-8 border-t border-slate-200 dark:border-slate-800 pt-8 mt-8">
			<h2 class="text-3xl font-bold bg-gradient-to-r from-violet-600 to-indigo-500 bg-clip-text text-transparent mb-6">
				Privacy Policy
			</h2>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">1. Introduction</h3>
			<p class="text-slate-600 dark:text-slate-300 mb-4">
				Your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website, TokenStork.com.
			</p>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">2. Information We Collect</h3>
			<p class="text-slate-600 dark:text-slate-300 mb-4">
				When you visit TokenStork.com, we try not to collect any information about you whatsoever, however CloudFlare and Vercel likely collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies installed on your device.
			</p>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">3. Use of Your Information</h3>
			<p class="text-slate-600 dark:text-slate-300 mb-4">
				We may use Google Analytics data generally to improve and optimize our site (for example, by generating analytics about how our customers browse and interact with the site, and to assess the success of our marketing and advertising campaigns).
			</p>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">4. Sharing Your Information</h3>
			<p class="text-slate-600 dark:text-slate-300 mb-4">
				We share your Device Information with third parties to help us use your Device Information, as described above. We use Google Analytics to help us understand how our customers use the site. You can read more about how Google uses your Personal Information <a href="https://www.google.com/intl/en/policies/privacy/" class="text-violet-600 hover:underline">here</a>. You can also opt-out of Google Analytics <a href="https://tools.google.com/dlpage/gaoptout" class="text-violet-600 hover:underline">here</a>.
			</p>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">5. Security</h3>
			<p class="text-slate-600 dark:text-slate-300 mb-4">
				We employ reasonable security measures to protect your information from unauthorized access, alteration, disclosure, or destruction.
			</p>

			<h3 class="text-xl font-semibold text-slate-900 dark:text-white mb-4">6. Contact Information</h3>
			<p class="text-slate-600 dark:text-slate-300">
				For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at <a href="mailto:hello@panmoni.com" class="text-violet-600 hover:underline">hello@panmoni.com</a>.
			</p>
		</section>
	</div>
</main>
