// app/components/FormatCategory.tsx
import { useState } from "react";

import { ClipboardIcon } from "@heroicons/react/outline";
import { Icon } from "@tremor/react";

import Toast from "@/app/components/Toast";

type FormatCategoryProps = {
  category: string;
};

export default function FormatCategory({ category }: FormatCategoryProps) {
  const [toastMessage, setToastMessage] = useState("");

  function showToast(message: string) {
    setToastMessage(message);
    setTimeout(() => {
      setToastMessage("");
    }, 3000);
  }

  function copyText(text: string) {
    navigator.clipboard.writeText(text);
    showToast("Category copied to clipboard");
  }

  const displayCategory =
    category.length > 10
      ? `${category.slice(0, 5)}...${category.slice(-5)}`
      : category;

  return (
    <>
      <a
        href={`https://explorer.salemkode.com/token/${category}`}
        target="_blank"
        rel="noopener noreferrer"
        title="View on SalemKode Explorer"
        className="font-mono"
      >
        {displayCategory}
      </a>
      <Icon
        icon={ClipboardIcon}
        size="sm"
        variant="simple"
        tooltip="Copy category to clipboard"
        onClick={() => copyText(category)}
        className="cursor-pointer align-middle hover:text-accent text-primary"
      />
      {toastMessage && <Toast message={toastMessage} />}
    </>
  );
}

// src/lib/components/FormatCategory.svelte
<script lang="ts">
	interface Props {
		category: string;
	}

	let { category }: Props = $props();
	let copied = $state(false);

	const display = $derived(
		category.length > 10 ? `${category.slice(0, 5)}...${category.slice(-5)}` : category
	);

	async function copy() {
		try {
			await navigator.clipboard.writeText(category);
			copied = true;
			setTimeout(() => (copied = false), 1500);
		} catch (err) {
			console.error(err);
		}
	}
</script>

<span class="inline-flex items-center gap-1.5">
	<a
		href={`https://explorer.salemkode.com/token/${category}`}
		target="_blank"
		rel="noopener noreferrer"
		title="View on SalemKode Explorer"
		class="font-mono text-xs text-slate-500 hover:text-violet-600"
	>
		{display}
	</a>
	<button
		onclick={copy}
		title="Copy category"
		class="text-primary hover:text-accent text-xs"
		aria-label="Copy category"
	>
		{#if copied}
			<span class="text-accent">✓</span>
		{:else}
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-4 w-4 inline">
				<path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
			</svg>
		{/if}
	</button>
</span>
